### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by kevin1232sn1** [ThomasReth/ITSS2#2]

**Comment by ThomasReth** [comment]
Hi,
yes it is still maintained. I'll upload a total new code base within the next two weeks.

**Comment by ThomasReth** [comment]
Hi,
Thank you! I'd like to mention I'm almost done with the implementation based on .NET 5. There will be a lot of improvements regarding the architecture (simpler, less coupling) and performance. In conjunction with that I'll provide at least a basic architecture documentation after the holidays. By the way, you should have a look to the official WWKS2 website as well.

**Comment by kevin1232sn1** [comment]
Sounds like you put a lot of work in it 👍 
Yeah we're looking into all documentation from WWKS2 :)
